INSERT INTO STUDENTI(redniBroj, ime, prezime, korisnickoIme, sifra) VALUES
(1, 'Eldin', 'Kecap', 'eldink', 'eldink'),
(2, 'Ademir', 'Musovic', 'ademirm', 'ademirm'),
(3, 'Husejn', 'Omerbasic', 'husejno', 'husejno'),
(4, 'Edin', 'Salihspahic', 'edins', 'edins'),
(5, 'Adnan', 'Babajic', 'adnanb', 'adnanb'),
(6, 'Adin', 'Beslagic', 'adinb', 'adinb'),
(7, 'Ramiz', 'Delic', 'ramizd', 'ramizd'),
(8, 'Emir', 'Fazlic', 'emirf', 'emirf'),
(9, 'Fatima', 'Ibreljic', 'fatimai', 'fatimai'),
(10, 'Camil', 'Omerovic', 'camilo', 'camilo'),
(11, 'Selma', 'Zrnic', 'selmaz', 'selmaz'),
(12, 'Miralem', 'Alic', 'miralema', 'miralema'),
(13, 'Tarik', 'Haracic', 'tarikh', 'tarikh'),
(14, 'Zvonimir', 'Madarac', 'zvonimirm', 'zvonimirm');
